name: Cassandra
version: "4.1.0"
slug: cassandra
description: Interface Cassandra pour Home Assistant
startup: services
boot: auto
init: false

arch:
  - amd64

ports:
  "8090/tcp": 8090

ports_description:
  "8090/tcp": Serveur web Cassandra

homeassistant_api: true

options: {}
schema: {}