name: Cassandra
version: "1.0.1"
slug: cassandra
description: Interface Cassandra pour Home Assistant
startup: services
boot: auto
init: false
arch:
  - amd64
ports:
  8090/tcp: 8090
ports_description:
  8090/tcp: Serveur web Cassandra
options: {}
schema: {}
